repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: check-secrets
        name: Check for secrets and credentials
        entry: scripts/check-secrets.sh
        language: script
        pass_filenames: false

      - id: check-personal-info
        name: Check for personal information
        entry: scripts/check-personal-info.sh
        language: script
        pass_filenames: false
