apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-secret-vars
  namespace: flux-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: flux-secret-vars
    creationPolicy: Owner
  data:
    - secretKey: dummy_route
      remoteRef:
        key: /home-prod/flux/dummy_route
    - secretKey: new_dummy_route
      remoteRef:
        key: /home-prod/flux/new_dummy_route
    - secretKey: paperless_route
      remoteRef:
        key: /home-prod/flux/paperless_route