---
# Namespace for ESO
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
# Flux HelmRepository for ESO
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
spec:
  interval: 10m
  url: https://charts.external-secrets.io
---
# ESO installation via HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: 0.16.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  values:
    installCRDs: true