apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            namespace: external-secrets
            key: secret-access-key