apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
# Define the middleware referenced in Ingress resources
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  targetNamespace: traefik
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "35.4.0"  # Latest version as of May 2025
      sourceRef:
        kind: HelmRepository
        name: traefik
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Global namespace for resources
    global:
      namespaceOverride: traefik
    # Deploy Traefik on the specified node pools
    deployment:
      enabled: true
    # Configure Traefik ports
    ports:
      web:
        port: 80
      websecure:
        port: 443
        # Enable TLS on the websecure port
        tls:
          enabled: true
    
    # Configure ACME (Let's Encrypt)
    certification:
      enabled: true
    
    # Let's Encrypt configuration
    certificatesResolvers:
      letsencrypt:
        acme:
          email: ${le_email_address}
          storage: /data/acme.json
          caServer: https://acme-staging-v02.api.letsencrypt.org/directory
          httpChallenge:
            entryPoint: web
    
    # Default TLS options
    tls:
      options:
        default:
          minVersion: VersionTLS12
          sniStrict: true
    
    # IPv6 support
    experimental:
      http3:
        enabled: true
    
    # IPv6 configuration
    service:
      ipFamilyPolicy: SingleStack
      ipFamilies:
        - IPv6
      annotations:
        metallb.universe.tf/allow-shared-ip: true
    
    # Default entrypoint for traffic
    entryPoints:
      web:
        address: ":80"
        # Configure HTTP to HTTPS redirection
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        address: ":443"
        http:
          tls:
            certResolver: letsencrypt  # Use the letsencrypt certResolver for Let's Encrypt
    
    # Additional Traefik configurations
    additionalArguments:
      - "--providers.kubernetesingress.ingressclass=traefik"
      - "--providers.kubernetescrd.ingressclass=traefik"
      
    # Persistent storage for Let's Encrypt certificates
    persistence:
      enabled: true
      path: /data
      size: 128Mi
