---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m0s
  targetNamespace: velero
  chart:
    spec:
      chart: velero
      version: "9.0.4"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  values:
    credentials:
      existingSecret: velero-credentials
    configuration:
      provider: aws
      backupStorageLocation:
        name: aws
        bucket: velero-backups
        config:
          region: eu-central-1
