---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m0s
  targetNamespace: velero
  chart:
    spec:
      chart: velero
      version: "9.0.4"
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
  values:
    credentials:
      existingSecret: velero-credentials
    # Core Velero configuration
    configuration:
      # Backup storage locations
      backupStorageLocations:
        - name: aws
          provider: aws
          bucket: home-prod-pg-backup
          config:
            region: eu-central-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-ext-secret
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: velero-credentials
    creationPolicy: Owner
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: home-prod-s3backup-key_id
        property: aws_access_key_id
    - secretKey: aws_secret_access_key
      remoteRef:
        key: home-prod-s3backup_access_key
        property: aws_secret_access_key