---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m0s
  targetNamespace: velero
  chart:
    spec:
      chart: velero
      version: "9.0.4"
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
  values:
    cleanUpCRDs: true
    credentials:
      existingSecret: velero-credentials
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.12.0
        volumeMounts:
          - name: plugins
            mountPath: /target
    configuration:
      # Backup storage locations
      backupStorageLocation:
        - name: aws
          provider: aws
          bucket: home-prod-pg-backup
          config:
            region: eu-central-1
      volumeSnapshotLocation:
        - name: aws
          provider: aws
          config:
            region: eu-central-1
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-ext-secret
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: velero-credentials
    creationPolicy: Owner
    # Use the built-in templating engine to assemble the .aws/credentials file
    template:
      type: Opaque
      data:
        cloud: |-
          [default]
          aws_access_key_id={{ .RemoteRef "home-prod-s3backup-key_id" }}
          aws_secret_access_key={{ .RemoteRef "home-prod-s3backup_access_key" }}
          region=eu-central-1