apiVersion: velero.io/v1
kind: Backup
metadata:
  name: paperless-test-backup2
  namespace: velero
spec:
  storageLocation: aws
  includedNamespaces:
    - paperless
  includedResources:
    - persistentvolumeclaims
    - pods
  labelSelector:
    matchLabels:
      velerobackup: yes
  snapshotVolumes: false