apiVersion: batch/v1
kind: Job
metadata:
  name: paperless-backup-111
  namespace: paperless
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: paperless-backup-sa
      restartPolicy: Never
      volumes:
        - name: export-volume
          emptyDir: {}
      initContainers:
        - name: exporter
          image: bitnami/kubectl:1.27
          command:
            - sh
            - -c
            - |
              set -e
              echo "[INFO] Locating Paperless pod..."
              PAPERLESS_POD=$(kubectl get pod -n paperless -l app.kubernetes.io/name=paperless -o jsonpath='{.items[0].metadata.name}')
              echo "[INFO] Found pod: $PAPERLESS_POD"
              echo "[INFO] Creating export directory in pod with correct permissions..."
              kubectl exec -n paperless "$PAPERLESS_POD" -c main -- sh -c "mkdir -p /library/export && chmod 777 /library/export"
              echo "[INFO] Running document_exporter inside pod..."
              kubectl exec -n paperless "$PAPERLESS_POD" -c main -- document_exporter /library/export
              echo "[INFO] Copying exported data from pod to shared volume..."
              kubectl cp paperless/"$PAPERLESS_POD":/library/export/. /export/
              echo "[INFO] Export completed successfully."
          volumeMounts:
            - name: export-volume
              mountPath: /export
      containers:
        - name: s3sync
          image: amazon/aws-cli:2.15.34
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: ACCESS_SECRET_KEY
            - name: AWS_DEFAULT_REGION
              value: eu-central-1
          command:
            - sh
            - -c
            - |
              set -e
              echo "[INFO] Syncing backup to S3..."
              aws s3 sync /export s3://home-prod-pg-backup/paperless-export/
              echo "[INFO] S3 sync completed."
          volumeMounts:
            - name: export-volume
              mountPath: /export
---
# 1. ServiceAccount for backup jobs
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paperless-backup-sa
  namespace: paperless
---
# 2. Role granting get/list on pods and exec on pods
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: paperless-backup-role
  namespace: paperless
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
---
# 3. Bind the Role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paperless-backup-rb
  namespace: paperless
subjects:
  - kind: ServiceAccount
    name: paperless-backup-sa
    namespace: paperless
roleRef:
  kind: Role
  name: paperless-backup-role
  apiGroup: rbac.authorization.k8s.io
