apiVersion: velero.io/v1
kind: Backup
metadata:
  name: paperless-test-backup12
  namespace: velero
spec:
  storageLocation: aws
  includedNamespaces:
    - paperless
  includedResources:
    - pods
    - persistentvolumeclaims
  labelSelector:
    matchLabels:
      velerobackup: yes
---
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: paperless-test-restore12
  namespace: velero
spec:
  backupName: paperless-test-backup12