apiVersion: velero.io/v1
kind: Backup
metadata:
  name: paperless-test-backup5
  namespace: paperless
spec:
  storageLocation: aws
  includedNamespaces:
    - paperless
  includedResources:
    - persistentvolumeclaims
    - pods
  labelSelector:
    matchLabels:
      velerobackup: yes