apiVersion: velero.io/v1
kind: Backup
metadata:
  name: paperless-test-backup12
  namespace: velero
spec:
  storageLocation: aws
  includedNamespaces:
    - paperless
  includedResources:
    - pods
    - persistentvolumeclaims
  labelSelector:
    matchLabels:
      velerobackup: yes