apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-creds
  namespace: paperless
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore

  target:
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
          username: "{{ .username }}"
          password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: home-prod-PAPERLESS_DBUSER

    - secretKey: password
      remoteRef:
        key: home-prod-PAPERLESS_DBPASS
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-creds
  namespace: paperless
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: home-prod-s3backup-key_id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: home-prod-s3backup_access_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secret
  namespace: paperless
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore

  target:
    name: paperless-secret
    creationPolicy: Owner

  data:
    - secretKey: PAPERLESS_DBENGINE
      remoteRef:
        key: home-prod-PAPERLESS_DBENGINE

    - secretKey: PAPERLESS_DBPORT
      remoteRef:
        key: home-prod-PAPERLESS_DBPORT

    - secretKey: PAPERLESS_DBNAME
      remoteRef:
        key: home-prod-PAPERLESS_DBNAME

    - secretKey: PAPERLESS_DBHOST
      remoteRef:
        key: home-prod-PAPERLESS_DBHOST

    - secretKey: PAPERLESS_DBUSER
      remoteRef:
        key: home-prod-PAPERLESS_DBUSER

    - secretKey: PAPERLESS_DBPASS
      remoteRef:
        key: home-prod-PAPERLESS_DBPASS

    - secretKey: PAPERLESS_ADMIN_USER
      remoteRef:
        key: home-prod-PAPERLESS_ADMIN_USER

    - secretKey: PAPERLESS_ADMIN_PASSWORD
      remoteRef:
        key: home-prod-PAPERLESS_ADMIN_PASSWORD

    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: home-prod-PAPERLESS_SECRET_KEY
