apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-creds
  namespace: paperless
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: home-prod-s3backup-key_id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: home-prod-s3backup_access_key
