apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-ext-secret
  namespace: paperless
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore

  target:
    name: paperless-secret
    creationPolicy: Owner

  data:
    - secretKey: PAPERLESS_DBENGINE
      remoteRef:
        key: home-prod-PAPERLESS_DBENGINE

    - secretKey: PAPERLESS_DBPORT
      remoteRef:
        key: home-prod-PAPERLESS_DBPORT

    - secretKey: PAPERLESS_DBNAME
      remoteRef:
        key: home-prod-PAPERLESS_DBNAME

    - secretKey: PAPERLESS_DBHOST
      remoteRef:
        key: home-prod-PAPERLESS_DBHOST

    - secretKey: PAPERLESS_DBUSER
      remoteRef:
        key: home-prod-PAPERLESS_DBUSER

    - secretKey: PAPERLESS_DBPASS
      remoteRef:
        key: home-prod-PAPERLESS_DBPASS

    - secretKey: PAPERLESS_ADMIN_USER
      remoteRef:
        key: home-prod-PAPERLESS_ADMIN_USER

    - secretKey: PAPERLESS_ADMIN_PASSWORD
      remoteRef:
        key: home-prod-PAPERLESS_ADMIN_PASSWORD

    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: home-prod-PAPERLESS_SECRET_KEY
