apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless
  namespace: paperless
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`${paperless_route}`)
      services:
        - kind: Service
          name: paperless
          port: 8000
  tls:
    certResolver: letsencrypt
  middlewares:
    - name: redirect-to-https
      namespace: default
