apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless
  namespace: paperless
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`$(PAPERLESS_URL)`)
      services:
        - kind: Service
          name: paperless
          port: 8000
