apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: paperless
  namespace: paperless
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`$(PAPERLESS_URL)`)
      kind: Rule
      services:
        - name: paperless
          port: 8000