apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless
  namespace: paperless
  labels:
    velero-backup: true
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: <your-storage-class> # Uncomment and set if needed
---
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: paperless-test-backup
  namespace: velero
spec:
  storageLocation: aws
  includedNamespaces:
    - paperless
  includedResources:
    - persistentvolumeclaims
    - pods
  labelSelector:
    matchLabels:
      velero-backup: true
  snapshotVolumes: false