apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless
  namespace: paperless
  labels:
    velerobackup: yes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
