apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless
  namespace: paperless
  labels:
    backup: paperless-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: <your-storage-class> # Uncomment and set if needed
---
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: paperless-pvc-backup
  namespace: velero
spec:
  storageLocation: aws
  includedNamespaces:
    - paperless
  includedResources:
    - persistentvolumeclaims
    - persistentvolumes
  labelSelector:
    matchLabels:
      backup: paperless-pvc
  snapshotVolumes: false